services:
  - type: web
    name: meihua-musical-instruments
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn factory_site.app:app --bind 0.0.0.0:$PORT
